image: gitpod/workspace-postgres
tasks:
  - name: streaming
    before: |
      gp sync-await before
      export DATABASE_URL=postgresql://gitpod@127.0.0.1:5432/postgres?sslmode=disable
    init: gp sync-await init
    command: |
      cd mastodon/
      NODE_ENV=development BIND=0.0.0.0 PORT=8008 STREAMING_CLUSTER_NUM=1 node ./streaming
  - name: sidekiq
    before: |
      gp sync-await before
      export DATABASE_URL=postgresql://gitpod@127.0.0.1:5432/postgres?sslmode=disable
      redis-server --daemonize yes
    init: gp sync-await init
    command: |
      cd mastodon/
      RAILS_ENV=development DB_POOL=5 bundle exec sidekiq -c 5
  - name: web
    before: |
      mkdir -p /workspace/.rvm
      export DATABASE_URL=postgresql://gitpod@127.0.0.1:5432/postgres?sslmode=disable
      rvm install 3.2.1
      brew install --ignore-dependencies libidn redis
      if [ -z "$GITTAG" ]; then export GITTAG=main; fi
      gp sync-done before
    init: |
      git clone -b "$GITTAG" https://github.com/mastodon/mastodon.git
      echo "$RUBY_VERSION" | cut -d- -f2 > mastodon/.ruby-version
      cd mastodon/
      git checkout "$GITTAG"
      bundle config --local build.idn-ruby --with-idn-dir="$(brew --prefix libidn)"
      bundle install
      yarn install
      echo "LOCAL_DOMAIN=$(gp url 8080 | cut -d/ -f3)" > .env
      cat ../.env.example >> .env
      echo "SECRET_KEY_BASE=$(RAILS_ENV=development bundle exec rake secret)" >> .env
      echo "OTP_SECRET=$(RAILS_ENV=development bundle exec rake secret)" >> .env
      RAILS_ENV=development bundle exec rake mastodon:webpush:generate_vapid_key >> .env
      RAILS_ENV=development rails db:setup
      RAILS_ENV=development NODE_OPTIONS='--openssl-legacy-provider' rails assets:precompile
      cd ..
      gp sync-done init
    command: |
      cd mastodon/
      RAILS_ENV=development BIND=0.0.0.0 PORT=8080 RAILS_SERVE_STATIC_FILES=true bundle exec puma -C config/puma.rb
  - name: admin account
    command: |
      gp sync-await init
      gp sync-await before
      cd mastodon/
      echo "E-mail address: admin@$(gp url 8080 | cut -d/ -f3)"
      RAILS_ENV=development bin/tootctl accounts modify admin --reset-password
      RAILS_ENV=development bin/tootctl accounts approve admin
ports:
  - port: 8080
    visibility: public
    onOpen: open-browser
  - port: 8008
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore
vscode:
  extensions:
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
